config/routes.rb
Rails.application.routes.draw do
  resources :reminders
  root 'home#index'

  get '/auth/strava', as: :strava_login
  get '/auth/strava/callback', to: 'sessions#create'

  get 'logout', to: 'sessions#destroy'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

  resources :users, only: [:create, :new, :destroy]

  get '/dashboard', to: 'dashboard#show'

  # get :feed, to: 'feed#index', as: 'feed'
  # get :buddies, to: 'buddies#index', as: 'buddies'
  # get :hangout, to: 'hangout#index', as: 'hangout'
  resources :record
  resources :user_plans, only: [:index, :show, :new, :update, :create]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
  belongs_to :plan

  has_many :user_plan_days
  has_many :user_plans, through: :user_plan_days
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user

  validates_presence_of :zip
end

app/models/plan.rb
class Plan < ApplicationRecord
  has_many :user_plans
  has_many :users, through: :user_plans

  has_many :days

end

app/models/remind_users.rb
class RemindUsers
  def initialize(time)
    @time = time
    @text_client = TwilioService.new
  end

  def send_messages
    Reminder.gather_data(@time).each do |reminder|
      workout = reminder.user.plans.order(:updated_at).first.days.first.workout
      @text_client.send_sms(reminder.phone_number, workout)
    end
  end
end

app/models/reminder.rb
require 'date'
# include ActionView::Helpers

class Reminder < ApplicationRecord
  belongs_to :user

  def remind_user
    start_date =  user.user_plans.last.start_date
    current_plan = user.plans.order(:updated_at).first
    until current_plan.days.last
      current_plan.days.each do |day|
        workout_today = day.workout
        reminder = "Hi #{self.user.name}. Get up and workout! Today: #{workout_today}."
      end
    end
    # start_date =  user.user_plans.last.start_date
    # TimeDifference.between(start_time, end_time).in_days
    # workout_day = start_date.each do |plan|
    #
    # end
  end

  def self.gather_data(time)
    where(set_at: time)
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password :validations => false
  has_many :locations
  has_many :user_plans
  has_many :reminders
  has_many :plans, through: :user_plans

  validates_presence_of :name
  validates_presence_of :email, uniqueness: true

  # def self.authenticate(email, password)
  # end

  def zip
    unless locations.empty?
      locations.first.zip
    else
      '80202'
    end
  end
end

app/models/user_plan.rb
class UserPlan < ApplicationRecord
  belongs_to :user
  belongs_to :plan

  validates_presence_of :start_date
end

app/models/user_plan_day.rb
class UserPlanDay < ApplicationRecord
  belongs_to :day
  belongs_to :user_plan

  validates_presence_of :run_date
end

app/models/weather.rb
class Weather
  attr_reader :zip

  def initialize(zip)
    @zip = zip
  end

  def data
    service = WeatherService.new(zip).current_weather





    # response = Faraday.get("http://api.openweathermap.org/data/2.5/weather?zip=80202&APPID=#{ENV['API_KEY']}&units=imperial")
    # JSON.parse(response.body)
  end

  def temp
    data['main']['temp'].to_i
  end

  def description
    data['weather'].first['description']
  end

  def city
    data['name']
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    binding.pry
    @presenter = DashboardPresenter.new(current_user)
    unless current_user
      redirect_to root_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show

  end

  def index

  end
end

app/controllers/record_controller.rb
class RecordController < ApplicationController
  def show
  
  end
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :set_reminder, only: [:show, :edit, :update, :destroy]

  def index
    @reminders = Reminder.all
    if @reminders.length.zero?
      flash[:alert] = 'You have no reminders. Create one now to get started.'
    end
  end

  def show
  end

  def new
    @reminder = current_user.reminders.new
  end

  def edit
  end

  def create
    # @reminder = Reminder.create!(reminder_params)
    @reminder = current_user.reminders.create(reminder_params)
    # binding.pry
    # @reminder.remind_user
    respond_to do |format|
      if @reminder.save
        format.html { redirect_to @reminder, notice: 'Reminder was successfully created.' }
        format.json { render :show, status: :created, location: @reminder }
      else
        format.html { render :new }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @reminder.update(reminder_params)
        format.html { redirect_to @reminder, notice: 'Reminder was successfully updated.' }
        format.json { render :show, status: :ok, location: @reminder }
      else
        format.html { render :edit }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @reminder.destroy
    respond_to do |format|
      format.html { redirect_to reminders_url, notice: 'Reminder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_reminder
      @reminder = Reminder.find(params[:id])
    end

    def reminder_params
      params.require(:reminder).permit(:phone_number, :set_at)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
   end

   def destroy
     session[:user_id] = nil
     redirect_to root_url
   end

  def create
    if auth_hash
      user = strava_omniauth
      session[:user_id] = user.id
      redirect_to dashboard_path
    else
      user = User.find_by(email: params['email'])
      if user && user.authenticate(params['password'])
        session[:user_id] = user.id
        redirect_to dashboard_path
      else
        flash[:error] = 'Invalid username and/or password. Please try again!'
        redirect_to login_path
      end
    end
  end

  def strava_omniauth
    user = User.find_or_create_by(uid: auth_hash['uid'])
    user.name = auth_hash['info']['first_name']+" "+auth_hash['info']['last_name']
    user.email = auth_hash['info']['email']
    user.uid = auth_hash['uid']
    user
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end





end

app/controllers/user_plans_controller.rb
class UserPlansController < ApplicationController
  def new
  end

  def create
    @current_plan = current_user.user_plans.create(plan_id: params[:plan][:id], start_date: params[:start_date])
    redirect_to user_plan_path(@current_plan)
  end

  def index
  end

  def show
    user_plan = UserPlan.find(params[:id])
    @days = user_plan.plan.days.order(:created_at).to_json

    @start_date = user_plan.start_date.to_json
    days_count = user_plan.plan.days.count

    @calendar_days = (0...days_count).map do |n|
      date = @start_date.to_date + n.days
      {
        year: date.year,
        month: date.month,
        day: date.day
      }
    end.to_json
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    # binding.pry
    @user = User.find(params[:user_id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      flash[:error] = "Invalid information"
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :zip)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/views/dashboard/show.html.erb
<div class="weather">
  <%= @presenter.temp %>ºF<br>
  <%= @presenter.description %><br>
  <%= @presenter.city %>
</div>

<h1 id='welcome'>Welcome, <%= current_user.name %>!</h1>
<div class="plan_links">
  <%= link_to "Add a Workout Plan", new_user_plan_path %></br>
  <%= link_to "Workout Plans", user_plan_path(current_user) %></br>
  <%= link_to "Record Run", record_path(current_user) %></br>
</div>

app/views/reminders/_form.html.erb
<%= form_with(model: reminder, local: true) do |form| %>
  <% if reminder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reminder.errors.count, "error") %> prohibited this reminder from being saved:</h2>

      <ul>
      <% reminder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="drop_down">
    <%= form.select(:set_at) do %>
      <%= [['6 am'], ['noon'], ['6 pm'], ['now']].each do |c| -%>
         <%= content_tag(:option, c.first, value: c.last) %>
       <% end %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reminders/edit.html.erb
<h1>Editing Reminder</h1>

<%= render 'form', reminder: @reminder %>

<%= link_to 'Show', @reminder %> |
<%= link_to 'Back', reminders_path %>

app/views/reminders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reminders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone number</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reminders.each do |reminder| %>
      <tr>
        <td><%= current_user.name %></td>
        <td><%= reminder.phone_number %></td>
        <td><%= reminder.set_at %></td>
        <td><%= link_to 'Show', reminder %></td>
        <td><%= link_to 'Edit', edit_reminder_path(reminder) %></td>
        <td><%= link_to 'Destroy', reminder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reminder', new_reminder_path %>

app/views/reminders/new.html.erb
<h1>New Reminder</h1>

<%= render 'form', reminder: @reminder %>

<%= link_to 'Back', reminders_path %>

app/views/reminders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= current_user.name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @reminder.phone_number %>
</p>

<p>
  <strong>Time:</strong>
  <%= @reminder.set_at %>
</p>

<%= link_to 'Edit', edit_reminder_path(@reminder) %> |
<%= link_to 'Back', reminders_path %>

app/views/user_plans/new.html.erb
<h2>Pick a Plan</h2>
<%= form_tag user_plans_path, method: 'post' do %>
  <%= collection_select(:plan, :id, Plan.all, :id, :name, prompt: true) %>
  <%= date_field_tag(:start_date) %>
  <%= submit_tag "Submit" %>
<% end %>

app/views/user_plans/show.html.erb
<%= link_to "Set up reminders?", new_reminder_path %>

<div id='calendar'></div>

<script type="text/javascript">
  $(function() {
    const calendar = $('#calendar');
    const days = JSON.parse('<%=raw @days %>');
    const calendarDays = JSON.parse('<%= raw @calendar_days %>');
    // debugger;
    const events = days.map(function(day, index) {
      let date = calendarDays[index];
      let eventData = {
        title: day.workout,
        start: new Date(date.year, date.month, date.day),
      }
      return eventData;
    });

    console.log(events)
    calendar.fullCalendar({
      header: {
        left: 'prev,next,today',
        center: 'title',
        right: 'month,agendaWeek,agendaDay'
        },
      events: events,
      selectable: true,
      selectHelper: true,
      editable: true,
      eventLimit: true,
      allDay: false,
      displayEventTime: false
    })
  });
</script>

app/views/users/new.html.erb
<h1>Let's start running!</h1>
<%= form_for @user do |f| %>
<div class="field">

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

</div>
<div class="submit">

  <%= f.submit %>
</div>

<% end %>